### ISSUE TITLE
Configuration changes required in Prometheus

### ISSUE THREAD

**Issue by roshu10** [prometheus/collectd_exporter#50]
Hey,

What are configuration change are we supposed to do in prometheus.yml file ?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
