### ISSUE TITLE
high availability for collectd_exporter

### ISSUE THREAD

**Issue by marcolan018** [prometheus/collectd_exporter#64]
is there a recommended installation/deployment option for collectd_exporter considering high availability? 

to run two exporters under load balancer, let prometheus talk to the node balancer but asks collectd client to talk to both exporter instances. Is this can work?

```
<Plugin network>
  Server "prometheus1.example.com" "25826"
</Plugin>
<Plugin network>
  Server "prometheus2.example.com" "25826"
</Plugin>
```

**Comment by steakknife** [comment]
This won't work and write_http doesn't scale because it's synchronous and N:1 fan-in. For large N, HA or reliability, it needs to use Kafka (write_kafka) and put the HA effort into Kafka. Then, Prometheus can be restarted without losing metrics because it will be batched in Kafka. This plugin needs to support Kafka too and make it automatically reconnect, since it'll be acting as a client, not a server.

**Comment by SuperQ** [comment]
Typically you run the collecd_exporter on localhost on targets. The recommended config should be

```
<Plugin network>
  Server "localhost" "25826"
</Plugin>
```

This allows the HA Prometheus instances to monitor all the targets directly. This also scales better, as Prometheus can scale out the scrapes on multiple target threads.
